# Inserts a blank line between shell prompts
add_newline = false
command_timeout = 5000

# Make truncation to 4 parent directories
[directory]
truncation_length = 2
truncate_to_repo = true
style = "cyan"
truncation_symbol = "…/"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[conda]
symbol = " "
format = "[$symbol$environment](dimmed green) "
ignore_base = false

[git_status]
ahead = "${count}"
diverged = "${ahead_count}${behind_count}"
behind = "${count}"
